version: '3.6'
services:
  samba:
    container_name: samba
    image: samba:latest
    ports:
      - 445:445
      - 139:139
      - 138:138
      - 137:137
    volumes:
      - /path/to/smb.conf:/etc/samba/smb.conf
      - /path/to/HDD:/mnt/HDD
      #- /run/media/user/Elements:/mnt/nataly
    environment:
      - user_count=2
      - user1=admin
      - password1=1234
      - user2=media
      - password2=1234
    restart: always
